http:
  port: "8081"

training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"

delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"
